export const LINKS = {
    reg: '/registration',
    auth: '/auth',
    main: '/',
    profile: '/profile',
    album: '/album',
    favorite: '/favorite',
    favoriteTracks: '/favorite/tracks',
    favoriteAlbums: '/favorite/albums',
    favoriteArtists: '/favorite/artists',
    favoritePodcasts: '/favorite/podcasts',
    weeklyTop: '/weekly',
    artistsTop: '/artists',
    billboard: '/billboard',
};
